---
title: "Trabalho extração"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Carregamento dos packages

```{r}
library(Biobase)
library(GEOquery)
```

Obtenção dos dados

```{r}
GDS5826 <- getGEO('GDS5826', destdir=".")

```


```{r}
sum(is.na(GDS5826))

data = GDS2eSet(GDS5826)
dim(data)
class(data)
```
Metadados
```{r}
Meta(GDS5826)$channel_count
Meta(GDS5826)$description
Meta(GDS5826)$feature_count
Meta(GDS5826)$platform
Meta(GDS5826)$sample_count
Meta(GDS5826)$sample_organism
Meta(GDS5826)$sample_type
Meta(GDS5826)$title
Meta(GDS5826)$type
```



```{r}
library(genefilter)
exp = exprs(data)
sds = rowSds(exp)
sum(is.na(sds))
sds=na.exclude(sds)
m = median(sds, na.rm=T)
m
hist(sds, breaks = 50, col = "mistyrose")
abline(v=m, col="blue",lwd = 4,lty = 2)
abline(v=m*2, col="red",lwd = 4,lty = 2)
datar = data[sds >=3*median(sds), ]
datar

```




```{r}
maximos = apply(exp,1,max)
minimos = apply(exp,1,min)
vl = maximos/minimos > 2
dataf=datar[vl,]
dataf

```



```{r}
meta = phenoData(data)
meta
varLabels(meta)
```


Analise diferencial
```{r}

datar$cell.type= factor(datar$cell.type)
table(datar$cell.type)

library(genefilter)
tt = rowttests(datar, "cell.type")
names(tt)
x=tt$p.value
rank = order(tt$p.value)
p20 = rank[1:20]
tt$p.value[p20]
```
Lista de 20 genes

```{r}
g = featureNames(datar[p20])
g

#falta poder corresponder o identificador ao nome do gene 
```

Heatmap


```{r}
data20=datar[p20,]
order_cols = order(data20$cell.type)
order_cols
data20 =data20[,order_cols]
heatmap(exprs(data20), Colv = NA, labCol = data20$cell.type)

```







####### clustering de genes e/ou amostras #######
```{r}


```



